---
title: "The GESIS Panel"
author: "Jan-Philipp Kolb"
date: "28 September 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Allgemeines

```{r}
wave <- "fb"
```



## 


```{r}
wavedatapath <- "J:/Work/GESISPanel_DATA/01_post_processing/c01/f_2018/fb/02_master/data/STATA14/"
```

```{r}
setwd(wavedatapath)
dat <- readstata13::read.dta13("fb_master_20180814_COMPLETE.dta",convert.factors = F)
```

```{r}
ncol(dat)
```

- Wieviele Variablen gibt es pro Welle




## Die Response Variable

```{r}
indvar_aapor <- grep("za006a",colnames(dat))

colnames(dat)[indvar_aapor]
```




```{r}
waves <- paste0(rep(letters[1:6],each=6,),rep(letters[1:6],6))
waves <- waves[-which(waves%in%c("ad","ae","af","fc","fd","fe","ff"))]

G_response_list <- list()
for (i in 1:length(waves)){
  ind_aapor <- which(colnames(dat)==paste0(waves[i],"za006a"))
  respvar <- dat[,ind_aapor]
  dat1 <- dat[!="-22",]
  G_response <- rep(0,nrow(dat1))
  G_response[dat1[,ind_aapor]%in%c("211","212","319","21121","211221")] <- 1
  G_response_list[[i]] <- G_response
}

sumtab_resp <- lapply(G_response_list,table)

sumtab_resp2 <- do.call(rbind, sumtab_resp)
```

```{r}
table(dat$D_response)
```

