---
title: "README"
author: "Jan-Philipp Kolb"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: md_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Part A - introduction

- A1 - [Laying the foundations in R](slides/a1_intro_r.md) ([Browser](slides/a1_intro_r.md) | [pdf](slides/a1_intro_r.pdf) | [rcode](rcode/a1_intro_r.R))

<!--
- [A2 - What is machine learning and why should you care](slides/intro_ml.Rmd)
- [Parallelization](doParallel.Rmd)
-->
## Part B - lasso and ridge regression

- [B1 - A small recap on linear regression](slides/b1_regression.md) ([Browser](slides/b1_regression.md) | [pdf](slides/b1_regression.pdf) | [rcode](rcode/b1_regression.R))
- [B2 - Using regularization to prevent overfitting and perform feature selection](slides/b2_regularization.md) ([Browser](slides/b2_regularization.md) | [pdf](slides/b2_regularization.pdf) | [rcode](rcode/b2_regularization.R))


<!--
- The `glmnet` package
-->


## Part C - Supervised Learning: Bagging and Boosting, tree-methods 

- [C1 - Supervised learning: tress and bagging](slides/c1_trees_bagging.md) ([Browser](slides/c1_trees_bagging.md) | [pdf](slides/c1_trees_bagging.pdf) | [rcode](rcode/c1_trees_bagging.R))

- [C2 - Supervised learning: random forests](slides/c2_random_forests.md) ([Browser](slides/c2_random_forests.md) | [pdf](slides/c2_random_forests.pdf) | [rcode](rcode/c2_random_forests.R))

- [C3 - Supervised learning: gradient boosting](slides/c3_gbm_regression.md) ([Browser](slides/c3_gbm_regression.md) | [pdf](slides/c3_gbm_regression.pdf) | [rcode](rcode/c3_gbm_regression.R))


## Part D - Supervised Learning: Neural Network

- [D - Supervised learning: neural network](slides/d_neuralNetworks.md) ([Browser](slides/d_neuralNetworks.md) | [pdf](slides/d_neuralNetworks.pdf) | [rcode](rcode/d_neuralNetworks.R))

## Part E - Unsupervised Learning: kmeans, hdbscan

- [E - Unsupervised Learning: kmeans, hdbscan](slides/e_Clustering.md)

## Part F - The dangers of machine learning

- [F - The dangers of machine learning](slides/f_dangers_ml.md)

## Part G - `reticulate` package: Umap

- [G - reticulate package: Umap](slides/g_reticulate_umap.md)

<!--
- work with python and R
-->

<!--
## Links

-   [Your First Machine Learning Project in R
    Step-By-Step](https://machinelearningmastery.com/machine-learning-in-r-step-by-step/)

-   chapter about machine learning in [awesome
    R](https://awesome-r.com/)

-   [Shiny App for machine
    learning](https://www.showmeshiny.com/machlearn/)

https://www.r-exercises.com/?s=machine+learning
-->