---
title: "The package caret"
author: "Jan-Philipp Kolb"
date: "21 November 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Loading the libraries

```{r}
library(MLmetrics)
library(party)
library(partykit)
library(caret)
```

## An example dataset

```{r}
n <-1000
gp.train.c <- data.frame(D_dropout=as.factor(sample(c("yes","no"),n,replace=T)),
                         sd_habit=runif(n),
                         sd_identify=runif(n),
                         another_var=as.factor(sample(c("yes","no","maybe"),n,replace=T)))
```

## Preliminaries

- No missing values are possible in the dataset


## 

```{r}
cvIndex <- caret::createFolds(gp.train.c$D_dropout, 10, returnTrain = T)
fiveStats <- function(...) c(twoClassSummary(...), defaultSummary(...))
  
ctrl  <- caret::trainControl(method = "cv",
                               number = 10,
                               index = cvIndex,
                               summaryFunction = fiveStats,
                               classProbs = TRUE)
```





```{r}
grid <- expand.grid(alpha = c(0,1),
                      lambda = seq(0.5,0,length=50))
```


```{r}
lasso<-caret::train( D_dropout ~  sd_habit + sd_identify +another_var ,
                     data=gp.train.c,method ='glmnet',
                     family= 'binomial',trControl = ctrl,
                     tuneGrid = grid,metric = 'Kappa')
```

<!--
https://github.com/topepo/caret/issues/145

https://github.com/topepo/caret/issues/330

https://discuss.analyticsvidhya.com/t/something-is-wrong-all-the-accuracy-metric-values-are-missing/64825
https://stackoverflow.com/questions/36181840/something-is-wrong-all-the-accuracy-metric-values-are-missing-error-in-caret
https://github.com/topepo/caret/issues/160
-->