---
title: "Conditional Inference Trees"
author: "Jan-Philipp Kolb"
date: "28 Juni 2019"
output: pdf_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## [ctree example](https://datawookie.netlify.com/blog/2013/05/package-party-conditional-inference-trees/)

```{r,eval=F}
install.packages("party")
```

## The data behind

```{r}
airq <- subset(airquality, !is.na(Ozone))
summary(airq$Temp)
```

## A first model

```{r}
library(party)
```


```{r}
air.ct <- ctree(Ozone ~ ., data = airq, controls = ctree_control(maxsurrogate = 3))
```


## The plot for `ctree`

```{r}
plot(air.ct)
```




## Recursive partitioning algorithms are special cases of a
simple two-stage algorithm

- First partition the observations by univariate splits in a recursive way and 
- second fit a constant model in each cell of the resulting partition.


## [`ctree` - Regression](https://stats.stackexchange.com/questions/171301/interpreting-ctree-partykit-output-in-r)

```{r}
library(partykit)
```

```{r,eval=F}
?ctree
```

```{r}
airq <- subset(airquality, !is.na(Ozone))
airct <- ctree(Ozone ~ ., data = airq)
plot(airct, type = "simple")
```

## Links

- [**Vignette**](https://cran.r-project.org/web/packages/partykit/vignettes/ctree.pdf) for package `partykit` 

